export const UPDATE_COUNTER = 'UPDATE_COUNTER';
export const RESET_COUNTER = 'RESET_COUNTER';
export const UPDATE_LIGHT_STATUS = 'UPDATE_LIGHT_STATUS';
export const UPDATE_CURRENT_TIME = 'UPDATE_CURRENT_TIME';
export const RESET_INITIAL_TIME = 'RESET_INITIAL_TIME';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_USER_ICON = 'UPDATE_USER_ICON';
