export const UPDATE_COUNTER = 'UPDATE_COUNTER';
export const UPDATE_LIGHT_STATUS = 'UPDATE_LIGHT_STATUS';
export const TICK = 'TICK';
export const RESTART_TIME = 'RESTART_TIME';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_USER_IMAGE = 'UPDATE_USER_IMAGE';
