export const INCREASE_COUNTER = 'INCREASE_COUNTER';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';
export const SWITCH_ON = 'SWITCH_ON';
export const SWITCH_OFF = 'SWITCH_OFF';
export const RESTART_TIME = 'RESTART_TIME';
export const TICK = 'TICK';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_USER_IMAGE = 'UPDATE_USER_IMAGE';
